name: coastalvegedge-detection-scivision
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - matplotlib
  - numpy
  - scipy
  - pandas
  - fsspec
  - pyyaml
  - requests
  - aiohttp
  - intake
  - intake-xarray
  - protobuf==3.2.0
  - pip
  - pip:
        - scivision==0.7.0
